version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
  eureka-server-service:
    image: eureka_server_service:latest
    restart: always
    container_name: eureka-server-service
    ports:
      - 8761:8761
  crud-service:
    image: crud_service:latest
    container_name: crud-service
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - eureka-server-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8761/eureka
  bonus-points-service:
    image: bonus_points_service:latest
    container_name: bonus-points-service
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - eureka-server-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8761/eureka